<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Bayar</name>
   <tag></tag>
   <elementGuidId>056d2516-4486-4c1b-aeb7-22118911dcb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.db .btn--title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[(text() = 'Bayar' or . = 'Bayar')]//span[text()='Bayar']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Masuk' or . = 'Masuk')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>29fcc00f-3ccd-4a66-bdb7-f7e36f6c0214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn--title</value>
      <webElementGuid>4c8f141c-d4b5-41e7-b2e7-d7d829d58e57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Masuk</value>
      <webElementGuid>18412a47-a50c-41fd-b271-547d2dfa613a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-a9a8b11d2c5cfb7f28fce41446f5a4b4</value>
      <webElementGuid>98fa49c8-baf8-426d-85dc-0cd841824584</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' db ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' btn--title ')]</value>
      <webElementGuid>ddafdd56-bbb5-4520-9070-2799e3b1039b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' db ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' btn--title ')]</value>
      <webElementGuid>938ccbcd-d0ac-454c-b3c9-3d97aabb6f00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Masuk' or . = 'Masuk')]</value>
      <webElementGuid>20250283-7c4e-41f4-b6db-32df9e1d7a76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
