<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>qdiv_Source Account</name>
   <tag></tag>
   <elementGuidId>06b25686-51a2-42af-9d1c-39203c003c53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.MuiInputBase-root.MuiInput-root.jss20.MuiInputBase-fullWidth.MuiInput-fullWidth.Mui-focused.Mui-focused > #select</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'select' and (text() = 'GiroAvailable BalanceIDR 2,120,941,950.00' or . = 'GiroAvailable BalanceIDR 2,120,941,950.00')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='select'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8c129055-1d60-4c06-b27b-76278132a047</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiSelect-root MuiSelect-select MuiSelect-selectMenu MuiInputBase-input MuiInput-input</value>
      <webElementGuid>0c90ef66-55e3-4a88-839d-419cf77918e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5120ab86-3cc7-4215-a192-a749f91d3142</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>25fb5e87-3769-4463-aaf2-3c3b7b8d52eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ee703507-e7d6-495a-bfcb-76b7ee3a0aad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7018c58c-db2d-4c1f-9c08-f10936cff22f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1de78e8b-18c8-4e87-acdb-e9b7cfde4eee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GiroAvailable BalanceIDR 2,120,941,950.00</value>
      <webElementGuid>0115e893-a073-4072-9e32-bf3f7f3024d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;pages container transaction&quot;]/div[@class=&quot;container--left&quot;]/div[@class=&quot;MuiGrid-root transaction transfer--container MuiGrid-container MuiGrid-justify-xs-center&quot;]/div[@class=&quot;MuiGrid-root transaction transfer--container MuiGrid-container MuiGrid-justify-xs-center&quot;]/div[@class=&quot;MuiGrid-root account-selector--container pv4 ph3 MuiGrid-item MuiGrid-grid-xs-12 MuiGrid-grid-md-10 MuiGrid-grid-xl-8&quot;]/div[@class=&quot;MuiGrid-root pb2 MuiGrid-container MuiGrid-spacing-xs-1&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-xs-12 MuiGrid-grid-md-10&quot;]/div[@class=&quot;MuiInputBase-root MuiInput-root  jss20  MuiInputBase-fullWidth MuiInput-fullWidth Mui-focused Mui-focused&quot;]/div[@id=&quot;select&quot;]</value>
      <webElementGuid>f1fa52b4-6fe1-493c-b304-1f292380cbad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='select'])[2]</value>
      <webElementGuid>d0daa5e0-19ee-41ca-8108-0cc70b262535</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div[4]/div/div/div/div[2]/div/div</value>
      <webElementGuid>cc7c0493-745f-4562-a770-dfa57b1b3022</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div[2]/div/div</value>
      <webElementGuid>38572cd6-f966-4753-ac1d-2cafb1d91a9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'select' and (text() = 'GiroAvailable BalanceIDR 2,120,941,950.00' or . = 'GiroAvailable BalanceIDR 2,120,941,950.00')]</value>
      <webElementGuid>8d47b222-c78d-4539-808a-c30f9794a934</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
