<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>qdiv_Transfer Type</name>
   <tag></tag>
   <elementGuidId>1d518dcf-465d-4ec3-8379-e9a2b76a8c22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.MuiInputBase-root.MuiInput-root.jss20.MuiInputBase-fullWidth.MuiInput-fullWidth.Mui-focused.Mui-focused > #select</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='select'])[3]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'select' and (text() = '​' or . = '​')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>37d68ff9-39fa-4902-9674-8858ae1d1f94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiSelect-root MuiSelect-select MuiSelect-selectMenu MuiInputBase-input MuiInput-input</value>
      <webElementGuid>b950f671-c498-4245-8b23-217ac410e067</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ed5fe393-941f-4c9e-9b6e-093ad70c9284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>3adb9f08-0964-4018-b799-0a242ba0b419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4c1731e8-bdf3-4ea1-a5ff-ae76cb53b77b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>bd344245-8291-4ee2-b21f-696ce4cefdaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6b2bc0d4-7a3c-4b92-afd4-9c8f713f9c14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>​</value>
      <webElementGuid>2720e637-bb08-42a3-8534-0ad827cbd8b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;pages container transaction&quot;]/div[@class=&quot;container--left&quot;]/div[@class=&quot;MuiGrid-root transaction transfer--container MuiGrid-container MuiGrid-justify-xs-center&quot;]/div[@class=&quot;MuiGrid-root transaction transfer--container MuiGrid-container MuiGrid-justify-xs-center&quot;]/div[@class=&quot;MuiGrid-root account-selector--container pv4 ph3 MuiGrid-item MuiGrid-grid-xs-12 MuiGrid-grid-md-10 MuiGrid-grid-xl-8&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container MuiGrid-spacing-xs-1&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-xs-12 MuiGrid-grid-md-10&quot;]/div[@class=&quot;MuiInputBase-root MuiInput-root  jss20  MuiInputBase-fullWidth MuiInput-fullWidth Mui-focused Mui-focused&quot;]/div[@id=&quot;select&quot;]</value>
      <webElementGuid>9a43cf59-a6b6-40a5-a324-7a746ea2b820</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='select'])[3]</value>
      <webElementGuid>c4b891cf-b5df-4f4b-920b-f4ce40f2ee89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div[4]/div/div/div[2]/div[2]/div/div</value>
      <webElementGuid>5235edcd-fed9-4887-87b0-522f12ffb6a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IDR 2,120,941,950.00'])[1]/following::div[5]</value>
      <webElementGuid>11bc068e-a747-42d0-9a54-42c5f4efa16c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Favorite'])[1]/preceding::div[7]</value>
      <webElementGuid>0a939ff1-f819-47f1-a86e-3128556e9c9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div</value>
      <webElementGuid>17e9d6c5-36d6-4ed8-a565-b9cd3c2622a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'select' and (text() = '​' or . = '​')]</value>
      <webElementGuid>2e4d3d17-9148-4cb4-a5c8-e2104c0e97eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
