<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Transfer</name>
   <tag></tag>
   <elementGuidId>d190c514-db96-4942-affb-0335654b737e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='transaction-tab-1']/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#transaction-tab-1 > span.MuiButton-label > span.MuiTab-wrapper</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bb32a422-c687-4975-a93d-35519650c646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTab-wrapper</value>
      <webElementGuid>fbc959ec-63e3-4aac-b81b-2c5be43c56a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Transfer</value>
      <webElementGuid>fa8e9757-fc73-4eb2-8760-e74ed652343e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;transaction-tab-1&quot;)/span[@class=&quot;MuiButton-label&quot;]/span[@class=&quot;MuiTab-wrapper&quot;]</value>
      <webElementGuid>7053fac6-84e9-48b3-bb97-62cc759131a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='transaction-tab-1']/span/span</value>
      <webElementGuid>9880eeb2-733f-4666-8010-1a920822db6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Giro'])[1]/preceding::span[12]</value>
      <webElementGuid>d1e50783-d04e-423d-beba-3a8d7914d43c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/span/span</value>
      <webElementGuid>447751df-c0b0-4f23-9775-b62200e930f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Transfer' or . = 'Transfer')]</value>
      <webElementGuid>93299c79-1f29-4f09-9820-236d9f75221f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
