<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Transaction</name>
   <tag></tag>
   <elementGuidId>b0a85ba4-00a2-4d2f-862b-0173372e3e37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='navlist-item-2']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#navlist-item-2 > span.MuiTab-wrapper</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4ce76614-8398-4e37-86b8-ec0bcfe80149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTab-wrapper</value>
      <webElementGuid>120d5931-baf5-4fc6-9ecf-d3f15b753d8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Transaction</value>
      <webElementGuid>4672bfff-ce8a-4007-b3ae-1177b0a0cbc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navlist-item-2&quot;)/span[@class=&quot;MuiTab-wrapper&quot;]</value>
      <webElementGuid>192490b3-4150-4abc-87f5-4f10029fa57d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='navlist-item-2']/span</value>
      <webElementGuid>fb4c260c-39e2-43fd-bde3-857ce9e406c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='U Transaction Account'])[1]/preceding::span[34]</value>
      <webElementGuid>a930554d-84dc-4fed-9e63-35921a5faf3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Transaction']/parent::*</value>
      <webElementGuid>a27ecc7b-cd94-4b01-a78d-2b05eb4424ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]/span</value>
      <webElementGuid>ba18c2b4-1799-478e-8521-2e272dc6b158</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Transaction' or . = 'Transaction')]</value>
      <webElementGuid>e2a19f2a-d83a-4d24-8b5f-723ba6a12454</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
