<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Konfirmasi</name>
   <tag></tag>
   <elementGuidId>834468a0-ff73-4d9c-97cc-118d97c27dec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.db .btn--title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[(text() = 'Konfirmasi' or . = 'Konfirmasi')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Masuk' or . = 'Masuk')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d0915845-4b2c-46b9-91a5-8f452638086f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn--title</value>
      <webElementGuid>08d5c9b5-06a3-4be4-858b-4c17cc1bc85f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Masuk</value>
      <webElementGuid>daaff281-5d6c-44a5-bcb9-8521e065c7ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-a9a8b11d2c5cfb7f28fce41446f5a4b4</value>
      <webElementGuid>e42dc5ee-aea1-4208-bc33-ef3344b6d416</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' db ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' btn--title ')]</value>
      <webElementGuid>a2136414-82f7-4f20-b4d5-0e9072d98178</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' db ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' btn--title ')]</value>
      <webElementGuid>67ad74f6-298f-4b74-a75a-41bb54df3510</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Masuk' or . = 'Masuk')]</value>
      <webElementGuid>9a3d41f1-13e6-4820-914e-4214a8f829fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
