Visual\ Grid\ View\ Port=" [[800,600],[1200,630]]"
API\ Key="WNSxc7p3SapkMYAZIfabwPW78TNOD1bVM0e5DsKFcLw110"
Server\ URL="https\://eyes.applitools.com/"
Application\ Name="Katalon Studio"
Match\ Level="STRICT"
