<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>qval_amountPulsa</name>
   <tag></tag>
   <elementGuidId>5fa1fde5-69ff-4469-8dc9-759061520f24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//li)[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
