<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>qbutton_Transaction</name>
   <tag></tag>
   <elementGuidId>2063fa87-84e4-4b5a-9dbb-f552e21ea126</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#navlist-item-2</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and @id = 'navlist-item-2' and (text() = 'Transaction' or . = 'Transaction')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c6d7e51d-f522-4008-8c91-447925aec2e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiTab-root MuiTab-textColorInherit hidden-xs dashboard--header-links</value>
      <webElementGuid>fd95095c-ed9e-46b5-a69a-1b1c3f5a0c98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>148acf59-2d09-40a4-a5cf-8d1d5fde6058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>30bc57a0-199a-4ac5-b9fe-2f343a537533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>c5249de6-ed0a-43ea-9482-9caaebf55fe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fe475791-b641-4215-8b24-f9c22608409c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>navlist-item-2</value>
      <webElementGuid>b9f656ab-0e44-4568-a148-a818e0fc14e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>navlist-item-navlist-2</value>
      <webElementGuid>572dba8c-6d43-4657-b03f-a77bb95c3abc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Transaction</value>
      <webElementGuid>bffdf98d-3acb-4588-8c52-3ee6498a5c72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navlist-item-2&quot;)</value>
      <webElementGuid>2bd4eab7-ce2b-472a-b60b-bd4938d35ea7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='navlist-item-2']</value>
      <webElementGuid>804fff52-c48d-47dd-bef8-959196bd53e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div/div[2]/div/div/div/button[3]</value>
      <webElementGuid>385eaba7-2776-44e8-81c5-c79f488baaf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='U Transaction Account'])[1]/preceding::button[8]</value>
      <webElementGuid>0f0ded36-7894-455a-a3a7-9b7d992b49bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]</value>
      <webElementGuid>6dec785f-b41e-4b09-8c2c-df856ef27c91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'navlist-item-2' and (text() = 'Transaction' or . = 'Transaction')]</value>
      <webElementGuid>ace419c7-a820-45cd-9074-2d18d86e7381</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
