<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>qimg_Maybank Logo</name>
   <tag></tag>
   <elementGuidId>7c83c834-7124-435b-98ad-c21265006de4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.logo</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@src = '/home/static/media/maybank-logo-white.28f0e9f7.svg' and @alt = 'Maybank2u']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c1c9b856-0628-4ad5-b1c8-fa4dfe5f880a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/home/static/media/maybank-logo-white.28f0e9f7.svg</value>
      <webElementGuid>7656a057-ab7c-4533-9fe3-3dd5771357d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>logo</value>
      <webElementGuid>e94947b4-2987-4333-ae45-1a2484deba19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Maybank2u</value>
      <webElementGuid>88889685-1bf2-43f7-8468-8b15c3b0886b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;pages container&quot;]/div[@class=&quot;container--left&quot;]/div[@class=&quot;MuiGrid-root common header  MuiGrid-container&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-xs-9 MuiGrid-grid-sm-3 MuiGrid-grid-md-4&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container&quot;]/a[@class=&quot;MuiTypography-root MuiLink-root MuiLink-underlineHover MuiTypography-colorPrimary&quot;]/img[@class=&quot;logo&quot;]</value>
      <webElementGuid>9d1b5f35-6bd6-46f1-9d73-5962a9c594c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div/div/div/a/img</value>
      <webElementGuid>6228c3f0-d921-48de-8383-f2eaffe446ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Maybank2u']</value>
      <webElementGuid>a8691804-15f2-4ce7-90ac-d30d0eeb6dbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>1d7fbd76-e9e0-4193-8a26-52b6f08a08a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/home/static/media/maybank-logo-white.28f0e9f7.svg' and @alt = 'Maybank2u']</value>
      <webElementGuid>20f6ae03-f76a-4d20-977c-65d39f59b2c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
