<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>qinput_Transfer Amount</name>
   <tag></tag>
   <elementGuidId>de80bbec-2a05-41f1-9f67-695f2f2a7d2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='transferAmount']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#transferAmount</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3eb11faf-e915-438a-a811-c88cd2238ef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>transferAmount</value>
      <webElementGuid>33bb86c0-46fb-4782-9eb9-1146952a2a38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>transferAmount</value>
      <webElementGuid>72fbbcf3-94cd-4de6-a4a9-500fbee794be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>933f7a65-bf4a-4b97-9533-486b16df2be1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>c7fb24f5-9af3-4af2-987d-3509a0ae99c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;transferAmount&quot;)</value>
      <webElementGuid>cf8618dc-0950-4866-99b1-fcac74e3d4c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='transferAmount']</value>
      <webElementGuid>8a4384b7-8e91-4001-a99b-1dcdafb3393d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div[2]/div/div/input</value>
      <webElementGuid>756d3406-72da-4594-9fe0-3b0dd2bb1009</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'transferAmount' and @name = 'transferAmount' and @type = 'text']</value>
      <webElementGuid>fcdaaab9-5c5c-444e-b156-cd7a982d293d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
