<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Transaction</name>
   <tag></tag>
   <elementGuidId>e5142885-19b8-4711-924c-6bbf7ab9312b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='navlist-item-2']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#navlist-item-2 > span.MuiTab-wrapper</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6f47d2b3-d96b-4289-9c3e-796bd5243a20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTab-wrapper</value>
      <webElementGuid>7c180d9b-ba95-4db4-911f-32aaad6c9124</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Transaction</value>
      <webElementGuid>85bdee95-5d0a-4844-ad91-92240d060098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navlist-item-2&quot;)/span[@class=&quot;MuiTab-wrapper&quot;]</value>
      <webElementGuid>1fd0d51f-d900-4a03-bc9f-7cf68c85259f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='navlist-item-2']/span</value>
      <webElementGuid>9ee6ad4c-529e-42c4-9a6c-94508f2f7ec0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='U Transaction Account'])[1]/preceding::span[34]</value>
      <webElementGuid>9d664585-315f-4fa7-af76-e201e168bf69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Transaction']/parent::*</value>
      <webElementGuid>b8e13f3e-f2ef-4055-8267-d6d2f3baa966</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]/span</value>
      <webElementGuid>3636907b-e4a9-4cd5-8e40-d91fd50ab2da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Transaction' or . = 'Transaction')]</value>
      <webElementGuid>b78e4011-aec0-4f21-8aae-579b555fb904</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
