<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>q_debitedAmount</name>
   <tag></tag>
   <elementGuidId>94ca4581-e441-4e2c-a95e-71c6a725f85f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//p)[29]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
