<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_Maybank Virtual Account</name>
   <tag></tag>
   <elementGuidId>814f9c04-067f-4399-a268-990196371a74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#login-password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[text()='Maybank Virtual Account']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'login-password' and @placeholder = 'Password' and @type = 'password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1a524c84-6ef3-472a-88ed-8f70a3513f66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>77996f77-4d07-49c8-9b55-91806b7c0417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1859ee5d-5ab3-4068-a740-323356211814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login-password</value>
      <webElementGuid>206a9037-6659-4d3f-9285-91b8dd514dd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>5b806a30-ec59-4840-9ff4-4b5647e2b8e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>0907c60e-f050-4076-9672-2e7cac336108</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>f6ad5c8f-a504-41b2-a75b-9ac62b621683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiInput-input</value>
      <webElementGuid>dc26a353-e463-4465-8364-176d2ae6927d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-dc52f1c9ff778f7a987d766b012ac487</value>
      <webElementGuid>47e37ee7-ae97-476d-96b5-2c25faec6543</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'login-password']</value>
      <webElementGuid>0dce604f-0c11-4b26-98e4-9fa1c6d17ff0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'login-password']</value>
      <webElementGuid>a50377ce-c739-4119-9846-0275fa5c634b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'login-password' and @placeholder = 'Password' and @type = 'password']</value>
      <webElementGuid>644ce0e2-5038-4c5f-9c17-5c9a94ba402e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
