<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_Pilih Bank</name>
   <tag></tag>
   <elementGuidId>65d070f8-94e1-44af-9381-1f8f3d994120</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[role=&quot;option&quot;]:nth-child(3)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div//input[@placeholder='Pilih Bank']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>03da0ac7-fd0c-47a8-a966-356c61f040db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiListItem-root MuiMenuItem-root   jss21 MuiMenuItem-gutters MuiListItem-gutters MuiListItem-button</value>
      <webElementGuid>2d82e7c6-42ef-4bbe-b772-e2ced5de9383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>dbe19c81-281c-430d-ae3d-4a85f2535735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>e1f5f4c2-fdb9-412e-a37c-aa133a294a1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b61aff2d-aad6-44b0-a732-8dce4a5db72d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>355df8cc-c152-45aa-8697-83845492bc57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Layanan Umum</value>
      <webElementGuid>235890e7-f166-4840-b97c-244d313b44d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-d8e3ca259a282ee70258f821bc844051</value>
      <webElementGuid>f2caeae6-0238-431a-91fb-3e7b29d16bad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(@role = 'option') and (position() = 3)]</value>
      <webElementGuid>fe8df091-1e0c-46f5-9b59-042c5ac69edc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[(@role = 'option') and (position() = 3)]</value>
      <webElementGuid>a2069226-a4a2-48f4-bae7-696d25d814e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Layanan Umum' or . = 'Layanan Umum')]</value>
      <webElementGuid>753f31b3-8cbe-4077-9a22-f0bbc9d58950</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
