<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_Transaction Payment Layanan Umum</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>72ce37f3-89b5-438e-8f5e-865c60350920</testSuiteGuid>
   <testCaseLink>
      <guid>7f59ebaf-d53b-4367-86eb-806424222754</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/M2U Web/Global/TC_Profile Chrome Katalon_Action</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d210fd0-3887-4596-b2d6-d797bc7cbcf0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e9101311-932f-452b-b631-8df33142ec26</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>363d5959-7338-4a5e-999f-db95dcf08698</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/M2U Web/Global/TC_Login_Action</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f52c303-eb84-4da7-8996-7a86e9096f4f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d37f7af-1ae0-41fa-983b-ddbeb4ccea51</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d647e5e3-151f-4139-965e-724a077fbf5e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/M2U Web/Postman/TC_Account Summary (List Account SOF)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>470347f1-1351-4c32-8685-e89e53b81376</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9d176157-d15c-478b-a557-528dd481d675</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/M2U Web/Purchase/TC_to Menu Transaction_Action</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>59d86d6a-9400-4ae6-8e9a-5d47234ad28f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/M2U Web/Payment/TC_to Pembayaran - Payment_Action</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>e0306cf1-c45c-4b45-897f-1fd33652ad87</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/M2U Web/Payment/TC_Payment_Action</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3926f27b-f053-43f4-9be1-997229d535ea</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bbb9bea5-d6c3-47a6-a1aa-d11483db94b6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a0cf875-8360-4466-92e8-867ca81908ec</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2e4629f5-5faf-41d0-86e3-3311e6b14d5d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/M2U Web/Payment/TC_Transaction Layanan Umum_Action</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>432a0906-f5b7-4cc6-a8d8-ef112864f3ca</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5253d9db-d3ed-4b12-b3c1-99c88a8a7bb5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/M2U Web/Payment/TC_Lanjut Bayar_Action</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>d644b582-12b6-49e8-a387-4d377622f8dc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/M2U Web/Global/TC_Confirmation Transaction_Action</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>cb9871b5-7062-41f0-9fe0-2d4c775f64dd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/M2U Web/Global/TC_Download Resi_Action</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>ded2ea02-bead-4962-8905-d503ade3ebe7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/M2U Web/Payment/TC_Close Resi Payment_Action</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>88d62b08-50e3-4f42-b685-fb42f9b2c34f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/M2U Web/Payment/TC_Pembayaran Baru_Action</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>d8f0e440-bf84-4315-9863-7b2e7b800f14</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/M2U Web/Global/TC_Close Browser_Action</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
