<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_Transaction Purchase</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>ab0c0cfb-9ec0-46a3-bd35-9da704f02f6f</testSuiteGuid>
   <testCaseLink>
      <guid>bf7ed4ed-2062-4a9e-b0e7-14d148ddd038</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/M2U Web/Global/TC_Profile Chrome Katalon_Action</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d210fd0-3887-4596-b2d6-d797bc7cbcf0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e9101311-932f-452b-b631-8df33142ec26</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>852987c6-e2c4-4e9f-9892-bd3d7059c41b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/M2U Web/Global/TC_Login_Action</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f52c303-eb84-4da7-8996-7a86e9096f4f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d37f7af-1ae0-41fa-983b-ddbeb4ccea51</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5525a335-2075-4a17-ab2c-c8ffe80ba640</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/M2U Web/Postman/TC_Account Summary (List Account SOF)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>470347f1-1351-4c32-8685-e89e53b81376</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a463215c-484a-4665-b197-9d928972d322</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/M2U Web/Purchase/TC_to Menu Transaction_Action</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>7d517dfb-532c-43c5-a82e-6bfc6de20395</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/M2U Web/Purchase/TC_to Pembelian - Purchase_Action</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>f7062e1c-cc28-4cb5-9b72-aa9c5f5f7f15</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/M2U Web/Purchase/TC_Purchase_Action</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a0734b2-aa21-4d6c-b6e1-ec57ce2adb09</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>086efbd5-b595-4727-8adb-f3dd4cf74a4b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c1160c81-8882-4e19-9897-178416b5bef6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3e2d0210-efc8-4842-bfac-5ea1c0d3258b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/M2U Web/Purchase/TC_Pulsa - Paket Data_Action</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad78fa11-4ffc-4782-9452-2529d87320c8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e613ea30-02fb-4097-ac22-3453003a6180</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c1c00e5c-be95-4ae7-b0d8-07583d97090f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ac7c69c8-ea87-4ffa-9348-09de6af3095f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/M2U Web/Global/TC_Confirmation Transaction_Action</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>4913ca92-8260-4e07-9a4c-da039ca0e008</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/M2U Web/Global/TC_Download Resi_Action</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>da7fa37f-9a30-4bf2-a938-40d1203a9f69</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/M2U Web/Purchase/TC_Close Resi Purchase Pulsa_Action</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>08b48364-b71a-43f6-86db-943d2b24e4a1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/M2U Web/Purchase/TC_Pembelian Baru_Action</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>c7719195-9645-45c0-b1c0-de97a1d3f200</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/M2U Web/Global/TC_Close Browser_Action</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
